language: node_js
node_js:
  - 'node'
  - 6
before_install:
  - npm install -g coveralls
script:
  - npm run lint
  - npm run build
  - npm run test
addons:
  chrome: stable
sudo: false
cache:
  directories:
    - node_modules
after_success:
  - npm run coverage
  - npm run coverage:report